[package]
name = "mepa"
version = "0.1.0"
edition = "2021"
authors = ["Jose <jabolina@protonmail.ch>"]

[dependencies]
bytes = "1"
tokio = { version = "1.15.0", features = ["full"] }

[dev-dependencies]
tokio = { version = "1.15.0", features = ["test-util"] }
